<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1118KPU" failures="1" tests="6" name="Personal Loan" time="0.095" errors="0" timestamp="2024-06-22T18:15:06 IST">
  <testcase classname="test.day1" name="Demo" time="0.02">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.Demo(day1.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.day1" name="secondTest" time="0.002"/>
  <testcase classname="test.day2" name="pLoan" time="0.002"/>
  <testcase classname="test.day4" name="LoginAPIHomeLoan" time="0.002"/>
  <testcase classname="test.day4" name="MobileloginHomeLoan" time="0.001"/>
  <testcase classname="test.day4" name="WebloginHomeLoan" time="0.002"/>
</testsuite> <!-- Personal Loan -->
